### ISSUE TITLE
How should I use the parser to set values in repeating segments

### ISSUE THREAD

**Issue by mohitmehra** [artifacthealth/hl7parser#1]
I have the following OBX segment:
'OBX|1|NM|C10390E614^Formula^L|volume|1|ml||N|||F||||',
    'OBX|2|NM|C10388E615^TPN+ 15% Dextrose+AminAcid+NaCl /kg+KCl  /kg+NaAce/kg+...^L|volume|14|ml||N|||F||||',
    'OBX|3|NM|C10388E616^Lipids 20%^L|volume|1.62|ml||N|||F||||'

I need to set OBX.15. 

Doing message.set('OBX.15', date) only changes the first line.

**Comment by meirgottlieb** [comment]
When specified in that way `OBX.15`, it is a shortcut to the first segment. If you need to access other repeating segments there are a number of different ways to do it. There are a few examples of working with segments in the [tests](https://github.com/artifacthealth/hl7parser/blob/master/tests/message.tests.ts). 

For example:
```
message.get("OBX").get(2).set("OBX.15", date);
```

or 

```
var segment = message.addSegment("OBX");
segment.set("OBX.15", date);
```

or

```
message.get("OBX").forEach(segment => segment.set("OBX.15", date));
```

Hope that helps!
