### ISSUE TITLE
How to access repeated properties? or differentiate between empty segments in repeated properties?

### ISSUE THREAD

**Issue by trsiddiqui** [artifacthealth/hl7parser#10]
I tried the following message which has repeated IN1 segment. How do i find the IN1.2.1 of the second instance of IN1? Or like in the example first instance of IN1 does not have an IN3 child but the second instance does, how do I point towards the IN3 of the first instance to find it empty?

MSH|^~\&|AcmeHIS|StJohn|ADT|StJohn|20050518073622||ADT^A01|MSGID20050518073622|P|2.3
PID|||12001||Jones^John^^^Mr.||19670822|M|||123 West St.^^Denver^CO^80020^USA||(850)555-0809|||||99345|460-99-2928
PV1||I|Main^802^1||||^Quacker^John|||IP|||||||||1|||||||||||||||||||||||||20050518073622
IN1|1|EPO|80|AETNA US HEALTHCARE|PO BOX 981114^""^EL PASO^TX^79998^""|||1500004000001|AETNA SERVICES INC|19|AETNA US HEALTHCARE|""|""||2|SOUTAR^RENEE^D|3|19700722|13324 WHITE CEMETERY RD^""^HANNIBAL^NY^130740000^""|||||||||||||||||124705454||||||1|F|225 GREENFIELD PARKWAY^^LIVERPOOL^NY^13088|185428
IN2|1||124705454||461-1200||||||
IN1|1|EPO|80|AETNA US HEALTHCARE|PO BOX 981114^""^EL PASO^TX^79998^""|||1500004000001|AETNA SERVICES INC|19|AETNA US HEALTHCARE|""|""||2|SOUTAR^RENEE^D|3|19700722|13324 WHITE CEMETERY RD^""^HANNIBAL^NY^130740000^""|||||||||||||||||124705454||||||1|F|225 GREENFIELD PARKWAY^^LIVERPOOL^NY^13088|185428
IN3|1||124705454||461-1200||||||
ORC|NW|20060307110114
OBR|1|20060307110114||003038^Urinalysis^L|||20060307110114

**Comment by meirgottlieb** [comment]
You find the IN1.2.1 of the second instance of IN1 as follows:
```
var message = hl7parser.create("...");
console.log(message.get("IN1").get(1).get("IN1.2.1").toString());
```

With regard to determining that the first IN1 does not have an IN3 but the second IN1 does. That is a little tricky because the IN3 is not a child of the IN1 in the way it is parsed. If you ask for the first IN3 you will get the IN3 you want to associated with the second IN1. In this case I would suggest looping through all segments so that way you can keep track of which IN1 the IN3 is associated with. For example:

```
var in1;
message.forEach(segment => {
    switch (segment.name) {
        case "IN1":
            in1 = segment;
            break;
        case "IN3":
            console.log(`${in1.get("IN1.4")}: ${segment.get("IN3.3")}`);
            break;
    }
});
```

**Comment by trsiddiqui** [comment]
Thanks.
