### ISSUE TITLE
[question] how to set a repeating field value?

### ISSUE THREAD

**Issue by kurttheviking** [artifacthealth/hl7parser#4]
Similar to https://github.com/artifacthealth/hl7parser/issues/1; is there a mechanism to set a repeating field value?

------

### Example

Assume the message was the following (an appropriate `MSH` would be present but is omitted below):

```txt
PID|1|16194|abc^^^^MRN~123^^^^ID||Jones^Bob
```

It's possible to get each *Patient ID* with the following:

```js
const hl7parser = require('hl7parser');

// ... load the message

message.get('PID.3').toArray().forEach(item => item.get('PID.3.1').toString());
```

Now, assume the system needed to construct a similar message:

```js
const hl7parser = require('hl7parser');

// ... use hl7parser.create to create a message with appropriate header

message.addSegment('PID');
```

What is the appropriate path address to set values in the repeating field?

I tried the following, among other techniques, though it doesn't appear to work:

```js
message.get('PID.3').get(0).set('PID.3.1', 'abc');
message.get('PID.3').get(0).set('PID.3.5', 'MRN');
message.get('PID.3').get(1).set('PID.3.1', 123);
message.get('PID.3').get(1).set('PID.3.5', 'ID');
```

**Comment by meirgottlieb** [comment]
Nice catch. I confirmed there is no way to set repeating fields if they don't already exist in the message. I need to think a bit about how this should work.

**Comment by meirgottlieb** [comment]
This issue is that Nodes are not created with calls to `message.get(...)` if they don't exist. The `get` method does not have side-effects. 

I've updated the `set` method so that it can be called with numbers as the path and without a value. If called without a value then it will ensure that the Node exists and return the Node. So you can now do:

```
message.set('PID.3').set(0).set('PID.3.1', 'abc');
message.set('PID.3').set(0).set('PID.3.5', 'MRN');
message.set('PID.3').set(1).set('PID.3.1', 123);
message.set('PID.3').set(1).set('PID.3.5', 'ID');
```

While I was at it I added the ability to chain setters. So you can now do this instead:
```
message.set('PID.3').set(0).set('PID.3.1', 'abc').set('PID.3.5', 'MRN');
message.set('PID.3').set(1).set('PID.3.1', 123).set('PID.3.5', 'ID');
```

or this:
```
message.set('PID.3').set(0).set(0, 'abc').set(4, 'MRN');
message.set('PID.3').set(1).set(0, 123).set(4, 'ID');
```

**Comment by kurttheviking** [comment]
@meirgottlieb &ndash; very helpful! Also, impressive response time; thank you!
