### ISSUE TITLE
Unix \n new lines

### ISSUE THREAD

**Issue by gvso** [artifacthealth/hl7parser#8]
I tried to follow what is recommended in #2 

I tried replacing `\n` characters with `\r` characters, but I get the following error:

`Error: Segment must have a name.`

Any possibility of supporting `\n` for testing purposes?

**Comment by GVSO** [comment]
Apparently, the data was not well-formatted. Thanks!

Even though, I think supporting `\n` for development purposes might be nice

**Comment by Brigadier1-9** [comment]
The "Segment must have a name" error occurs if the HL7 text has a trailing delimiter at the end of the final segment; this was happening to me when I was reading sample messages from a file for example.

Although not strictly speaking 'in spec', it may be an idea to strip any trailing delimiter from the message string prior to conversion

**Comment by meirgottlieb** [comment]
It's easy enough for users of the library replace \n with \r and trim whitespace when needed. I don't see any reason to include this as part of the lib.
