### ISSUE TITLE
Index 1 of MSH is pipe character (|)

### ISSUE THREAD

**Issue by GVSO** [artifacthealth/hl7parser#9]
Getting field with index 1 works perfectly for all segments but MSH.

```
var hl7parser = require("hl7parser");

var message = hl7parser.create("MSH|^~\&|||||20121031232617||ADT^A04|20381|P|2.3||||NE\rEVN|A04|20121031162617||01\rPID|1|16194|16194||Jones^Bob");
console.log(message.get("MSH.1").toString()); // prints "|" instead of "^~\&"
```

I don't know if this is a bug (it looks like it). Even so, it's not a big issue, but still a little annoying.

**Comment by meirgottlieb** [comment]
This is correct behavior. The field separator is MSH.1. The encoding characters are MSH.2. Then MSH.3 is the first normal field, “Sending Application”. See https://corepointhealth.com/resource-center/hl7-resources/hl7-msh-message-header.

**Comment by GVSO** [comment]
I see. Thanks for clarifying

Also, thank you very much for this awesome library!

**Comment by meirgottlieb** [comment]
Sure thing!
